BULK INSERT [dbo].[Instructor]
FROM 'FILE PATH HERE'
WITH (FIRSTROW = 3,
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n')

BULK INSERT [dbo].[Student]
FROM 'FILE PATH HERE'
WITH (FIRSTROW = 3,
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n')

BULK INSERT [dbo].[Section]
FROM 'FILE PATH HERE'
WITH (FIRSTROW = 3,
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n')

BULK INSERT [dbo].[Course_Fact_Table]
FROM 'FILE PATH HERE'
WITH (FIRSTROW = 3,
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n')

BULK INSERT [dbo].[Course]
FROM 'FILE PATH HERE'
WITH (FIRSTROW = 3,
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n')
